# Generated by Django 4.2.1 on 2023-06-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_publication_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
